In [5]:
import pandas as pd

df = pd.read_csv("donnees_analyse/retards_hdf.csv", sep=";")

In [6]:
df.shape

(73308, 23)

In [7]:
df.dtypes

trip_id                 str
numero_train        float64
date_service          int64
ligne                   str
nom_ligne               str
stop_id                 str
gare                    str
hauts_de_france       int64
latitude            float64
longitude           float64
ordre_arret         float64
heure_prevue            str
retard_secondes       int64
retard_minutes      float64
en_retard             int64
statut_train            str
statut_arret            str
type_observation        str
pluie_mm            float64
neige_cm            float64
temperature         float64
vent_kmh            float64
rafales_kmh         float64
dtype: object

In [8]:
df.head()

,trip_id,numero_train,date_service,ligne,nom_ligne,stop_id,gare,hauts_de_france,latitude,longitude,...,retard_minutes,en_retard,statut_train,statut_arret,type_observation,pluie_mm,neige_cm,temperature,vent_kmh,rafales_kmh
0,OCESN9864F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,30.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
1,OCESN9868F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,30.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
2,OCESN9836F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,0.0,0,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
3,OCESN839172F1187_F:TER:FR:Line::9d60af5b-0820-...,839172.0,20261008,K1,PARIS - STRASBOURG,StopPoint:OCETrain TER-87116582,Château-Thierry,1,49.03814,3.409302,...,5.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
4,OCESN839171F1187_F:TER:FR:Line::9d60af5b-0820-...,NaN,20261008,NaN,NaN,StopPoint:OCETrain TER-87116582,Château-Thierry,1,49.03814,3.409302,...,0.0,0,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN

In [9]:
df.head()

,trip_id,numero_train,date_service,ligne,nom_ligne,stop_id,gare,hauts_de_france,latitude,longitude,...,retard_minutes,en_retard,statut_train,statut_arret,type_observation,pluie_mm,neige_cm,temperature,vent_kmh,rafales_kmh
0,OCESN9864F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,30.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
1,OCESN9868F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,30.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
2,OCESN9836F1187_F:OUI:FR:Line::A6C76228-9224-4C...,NaN,20261008,NaN,NaN,StopPoint:OCETGV INOUI-87223263,Lille Europe,1,50.63940,3.075721,...,0.0,0,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
3,OCESN839172F1187_F:TER:FR:Line::9d60af5b-0820-...,839172.0,20261008,K1,PARIS - STRASBOURG,StopPoint:OCETrain TER-87116582,Château-Thierry,1,49.03814,3.409302,...,5.0,1,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN
4,OCESN839171F1187_F:TER:FR:Line::9d60af5b-0820-...,NaN,20261008,NaN,NaN,StopPoint:OCETrain TER-87116582,Château-Thierry,1,49.03814,3.409302,...,0.0,0,PREVU,PREVU,CONSTATE,NaN,NaN,NaN,NaN,NaN

In [10]:
(df.isna().mean() * 100).round(1).sort_values(ascending=False)

vent_kmh            6.8
temperature         6.8
pluie_mm            6.8
rafales_kmh         6.8
neige_cm            6.8
ordre_arret         6.6
heure_prevue        6.6
ligne               6.5
nom_ligne           6.5
numero_train        6.5
date_service        0.0
gare                0.0
stop_id             0.0
trip_id             0.0
latitude            0.0
en_retard           0.0
retard_minutes      0.0
retard_secondes     0.0
longitude           0.0
hauts_de_france     0.0
type_observation    0.0
statut_train        0.0
statut_arret        0.0
dtype: float64